@startuml

[*] -> idle
idle: isWalking = false
idle: isAttacking = false
idle -> walk_front
idle -> walk_side
idle -> walk_back
idle -> attack

walk_front: isWalking = true
walk_front: direction = 1
walk_front: isAttacking = false
walk_front -> idle
walk_front -> walk_side
walk_front -> walk_back
walk_front -> attack

walk_side: isWalking = true
walk_side: direction = 2
walk_side: isAttacking = false
walk_side -> idle
walk_side -> walk_front
walk_side -> walk_back
walk_side -> attack

walk_back: isWalking = true
walk_back: direction = 3
walk_back: isAttacking = false
walk_back -> attack
walk_back -> idle
walk_back -> walk_front
walk_back -> walk_side

attack: isAttacking = true


@enduml